services:
  
  alpdeskcore.listener.contao_generatesymlinks:
    class: Alpdesk\AlpdeskCore\Events\Listener\AlpdeskCoreEventContaoGenerateSymlinkListener
    tags:
      - { name: kernel.event_listener, event: contao.generate_symlinks}   